[package]
name = "BuilderIcons"
version = "0.1.0"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!*.storybook.lua",
    "!*.story.lua",
]
publish = true
authors = ["Nick Winans <nwinans@roblox.com>"]
description = "Icons for Roblox powered by fonts"
repository = "https://github.com/Roblox/builder-icons"
keywords = [
    "icons",
    "fonts",
]
homepage = "https://icons.foundation.roblox.com"
documentation = "https://icons.foundation.roblox.com"
[dev_dependencies.React]
version = "^17.0.6"

[dev_dependencies.Roact]
package = "RoactCompat"
version = "^17.0.6"
