[package]
name = "Foundation"
version = "1.41.2"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!*.test.lua",
    "!*.bench.lua",
    "!*.snap.lua",
    "!Utility/benchmarks.lua",
    "!*.csv",
]
publish = true
authors = [
    "Nick Winans <nwinans@roblox.com>",
    "Andrea Fletcher <afletcher@roblox.com>",
    "Rikesh Subedi <rsubedi@roblox.com>",
]
description = "Ready-to-use foundational React Luau components."
repository = "https://github.com/Roblox/foundation"
keywords = [
    "foundation",
    "react",
    "ui",
    "components",
]
homepage = "https://foundation.roblox.com"
documentation = "https://foundation.roblox.com"
[dependencies.BuilderIcons]
version = "^0.1.6"

[dependencies.Cryo]
version = "^1.1.0"

[dependencies.Dash]
version = "^2.0.0"

[dependencies.FoundationImages]
version = "^1.19.0"

[dependencies.Lumberyak]
package = "lumberyak"
version = "^0.1.1"

[dependencies.Motion]
version = "^0.1.0"

[dependencies.Otter]
version = "^1.3.3"

[dependencies.RbxDesignFoundations]
version = "^2.0.155"

[dependencies.React]
version = "^17.0.6"

[dependencies.ReactIs]
version = "^17.0.6"

[dependencies.ReactOtter]
version = "^1.3.3"

[dependencies.ReactRoblox]
version = "^17.0.6"

[dependencies.ReactUtils]
version = "^1.9.0"

[dependencies.Roact]
package = "RoactCompat"
version = "^17.0.6"

[dependencies.SafeFlags]
version = "^0.1.0"

[dependencies.UsageTracker]
version = "^0.1"
[dev_dependencies.DocUtils]
version = "^0.1.13"

[dev_dependencies.FoundationTestingLibrary]
package = "FoundationTestingLibrary"
version = "^0.1.2"

[dev_dependencies.Jest]
version = "^3.11.1"

[dev_dependencies.JestBenchmark]
version = "^3.11.1"

[dev_dependencies.JestGetType]
version = "^3.11.1"

[dev_dependencies.JestGlobals]
version = "^3.11.1"

[dev_dependencies.LuaYaml]
version = "^0.1.0"

[dev_dependencies.ReactTestingLibrary]
version = "^12.3.4"

[dev_dependencies.ReactTestingUtils]
version = "^1.3.1"

[dev_dependencies.Rhodium]
version = "^0.5.0"
