--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent._Index

local Package = require(PackageIndex["ExperienceChat-44870566-f93a1416"]["ExperienceChat"])

return Package
