[package]
name = "JestCircus"
version = "3.8.0"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
    "!**/__mocks__/**",
]
publish = true
authors = [
    "Chris Trześniewski <k.trzesniewski@gmail.com>",
    "Ignacio Falk <flakolefluk@gmail.com>",
    "Ishan Mundra <imundra@roblox.com>",
    "Matt Hargett <plaztiksyke@gmail.com>",
    "Olivier Trepanier <otrepanier@roblox.com>",
    "Raymond Ng <raymondng@berkeley.edu>",
]
license = "MIT"
[dependencies.ChalkLua]
version = "^0.2.0"

[dependencies.Expect]
package = "Expect"
version = "^3.8.0"

[dependencies.JestEach]
package = "JestEach"
version = "^3.8.0"

[dependencies.JestEnvironment]
package = "JestEnvironment"
version = "^3.8.0"

[dependencies.JestMatcherUtils]
package = "JestMatcherUtils"
version = "^3.8.0"

[dependencies.JestMessageUtil]
package = "JestMessageUtil"
version = "^3.8.0"

[dependencies.JestRuntime]
package = "JestRuntime"
version = "^3.8.0"

[dependencies.JestSnapshot]
package = "JestSnapshot"
version = "^3.8.0"

[dependencies.JestTestResult]
package = "JestTestResult"
version = "^3.8.0"

[dependencies.JestTypes]
package = "JestTypes"
version = "^3.8.0"

[dependencies.JestUtil]
package = "JestUtil"
version = "^3.8.0"

[dependencies.LuauPolyfill]
version = "^1"

[dependencies.PrettyFormat]
package = "PrettyFormat"
version = "^3.8.0"

[dependencies.Promise]
version = "^3.3.0"

[dependencies.RegExp]
version = "^0.2.1"

[dependencies.RobloxShared]
package = "RobloxShared"
version = "^3.8.0"

[dependencies.Throat]
package = "Throat"
version = "^3.8.0"
